"""empty message

Revision ID: 3b1a20d68abf
Revises: 
Create Date: 2024-04-01 15:54:40.436921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1a20d68abf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.CHAR(length=64), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z]{2,}$'"),
    sa.CheckConstraint('length(email) >= 5'),
    sa.CheckConstraint('length(name) <= 128'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('heading', sa.VARCHAR(length=128), nullable=False),
    sa.Column('text', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('picture', sa.CHAR(length=64), nullable=True),
    sa.Column('private', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id_user'), 'post', ['id_user'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('id_post', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=512), nullable=False),
    sa.CheckConstraint('length(text) >= 2'),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_id_post'), 'comment', ['id_post'], unique=False)
    op.create_index(op.f('ix_comment_id_user'), 'comment', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_id_user'), table_name='comment')
    op.drop_index(op.f('ix_comment_id_post'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_post_id_user'), table_name='post')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
