"""empty message

Revision ID: 905aa089b30f
Revises: 3b1a20d68abf
Create Date: 2024-04-01 16:45:02.329323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905aa089b30f'
down_revision: Union[str, None] = '3b1a20d68abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_registry', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_registry')
    # ### end Alembic commands ###
